import Link from "next/link";
import { CallButton, ClosingCta, Footer, Header } from "./chrome";
import BloomingMagnolia from "./motion/BloomingMagnolia";
import { Reveal, RevealGroup, RevealItem } from "./motion/Reveal";
import { formatGuideDate, type Guide } from "@/lib/guides";
import { site } from "@/lib/site";

/* Shared furniture for a guide.
 *
 * The prose primitives exist so that five long articles cannot drift into
 * five slightly different typographic systems, which is what happens when
 * long-form pages are each styled by hand. */

export function H2({ children, id }: { children: React.ReactNode; id?: string }) {
  return (
    <h2 id={id} className="mt-16 scroll-mt-24 text-[2rem] leading-tight lg:text-[2.3rem]">
      {children}
    </h2>
  );
}

export function H3({ children }: { children: React.ReactNode }) {
  return (
    <h3 className="mt-10 font-display text-[1.55rem] font-bold leading-snug text-ink">
      {children}
    </h3>
  );
}

export function P({ children }: { children: React.ReactNode }) {
  return <p className="mt-5 text-xl leading-relaxed text-ink-soft">{children}</p>;
}

/* Opening paragraph of a section, set a size up so a skimmer who reads
 * only the first line of each section still gets the argument. */
export function Lead({ children }: { children: React.ReactNode }) {
  return <p className="mt-5 text-2xl leading-relaxed text-ink">{children}</p>;
}

export function UL({ children }: { children: React.ReactNode }) {
  return (
    <ul className="mt-6 space-y-3.5 text-xl leading-relaxed text-ink-soft">
      {children}
    </ul>
  );
}

export function LI({ children }: { children: React.ReactNode }) {
  return (
    <li className="relative pl-7">
      <span
        className="absolute left-0 top-[0.72em] h-2 w-2 rounded-full bg-[var(--accent)]"
        aria-hidden="true"
      />
      {children}
    </li>
  );
}

/* Numbered steps. A real <ol> so it reads correctly to a screen reader and
 * so the numbers survive a copy and paste into an email to a sibling. The
 * number is passed explicitly rather than generated by a CSS counter,
 * because a counter renders nothing at all if the utility that produced it
 * is ever purged, and a silently unnumbered set of steps is worse than a
 * slightly more verbose call site. */
export function Steps({ children }: { children: React.ReactNode }) {
  return <ol className="mt-8 space-y-9">{children}</ol>;
}

export function Step({
  n,
  title,
  children,
}: {
  n: number;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <li className="relative border-l-2 border-[var(--accent-wash)] pl-8">
      <span
        className="absolute -left-[15px] top-0.5 flex h-7 w-7 items-center justify-center rounded-full bg-[var(--accent)] text-base font-bold text-white"
        aria-hidden="true"
      >
        {n}
      </span>
      <h3 className="font-display text-[1.45rem] font-bold leading-snug text-ink">
        {title}
      </h3>
      <div className="[&>p:first-child]:mt-3">{children}</div>
    </li>
  );
}

export function A({ href, children }: { href: string; children: React.ReactNode }) {
  const external = href.startsWith("http");
  const cls =
    "font-semibold text-pink underline decoration-pink-soft decoration-2 underline-offset-4 transition-colors duration-200 hover:decoration-pink";
  if (external) {
    return (
      <a href={href} className={cls} rel="noopener">
        {children}
      </a>
    );
  }
  return (
    <Link href={href} className={cls}>
      {children}
    </Link>
  );
}

/* A pulled-out point. Used sparingly: if everything is a callout, nothing
 * is, and this readership does not benefit from a decorated page. */
export function Callout({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <aside className="mt-10 rounded-panel border-l-4 border-[var(--accent)] bg-[var(--accent-wash)] p-7 sm:p-8">
      <h3 className="font-display text-[1.4rem] font-bold leading-snug text-ink">
        {title}
      </h3>
      <div className="[&>p]:text-ink-soft [&>p:first-child]:mt-3">{children}</div>
    </aside>
  );
}

/* The one thing on the page a reader might want to write down. */
export function KeyNumber({
  value,
  label,
  note,
}: {
  value: string;
  label: string;
  note?: string;
}) {
  return (
    <div className="rounded-panel border border-rule bg-page p-7">
      <p className="font-display text-[2.4rem] font-bold leading-none text-[var(--accent)]">
        {value}
      </p>
      <p className="mt-3 text-lg font-semibold text-ink">{label}</p>
      {note && <p className="mt-1.5 text-base text-ink-faint">{note}</p>}
    </div>
  );
}

export function KeyNumbers({ children }: { children: React.ReactNode }) {
  return <div className="mt-10 grid gap-5 sm:grid-cols-3">{children}</div>;
}

/* Every factual claim in these guides traces back to a primary source, and
 * the reader gets to see them. Care decisions are consequential enough
 * that "trust me" is not good enough. */
export function Sources({
  items,
}: {
  items: { label: string; href: string }[];
}) {
  return (
    <section className="mt-20 border-t border-rule pt-10">
      <h2 className="text-base font-bold uppercase tracking-[0.18em] text-green">
        Where these figures come from
      </h2>
      <ul className="mt-6 space-y-3 text-lg text-ink-soft">
        {items.map((s) => (
          <li key={s.href}>
            <a
              href={s.href}
              rel="noopener nofollow"
              className="underline decoration-rule decoration-2 underline-offset-4 transition-colors duration-200 hover:text-pink hover:decoration-pink-soft"
            >
              {s.label}
            </a>
          </li>
        ))}
      </ul>
      <p className="mt-6 text-base text-ink-faint">
        Benefit rules and rates change. Figures were checked on{" "}
        {formatGuideDate("2026-08-25")}. Always confirm current numbers with
        the agency that administers the program.
      </p>
    </section>
  );
}

/* This is general information, not advice about a specific person's case,
 * and on Medicaid and VA topics that distinction matters legally as well
 * as ethically. Said plainly rather than in small print. */
export function NotAdvice({ children }: { children: React.ReactNode }) {
  return (
    <p className="mt-10 border-l-2 border-rule pl-6 text-lg italic text-ink-faint">
      {children}
    </p>
  );
}

export function GuideShell({
  guide,
  children,
  sources,
}: {
  guide: Guide;
  children: React.ReactNode;
  sources: { label: string; href: string }[];
}) {
  const url = `${site.url}/guides/${guide.slug}`;

  const jsonLd = [
    {
      "@context": "https://schema.org",
      "@type": "BlogPosting",
      headline: guide.title,
      description: guide.description,
      datePublished: guide.published,
      dateModified: guide.updated,
      mainEntityOfPage: { "@type": "WebPage", "@id": url },
      author: { "@type": "Person", name: site.founder },
      publisher: {
        "@type": "Organization",
        name: site.name,
        url: site.url,
      },
      about: guide.category,
      isAccessibleForFree: true,
    },
    {
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      itemListElement: [
        { "@type": "ListItem", position: 1, name: "Home", item: site.url },
        {
          "@type": "ListItem",
          position: 2,
          name: "Guides",
          item: `${site.url}/guides`,
        },
        { "@type": "ListItem", position: 3, name: guide.title, item: url },
      ],
    },
  ];

  return (
    <>
      <Header />
      <main
        id="main"
        style={
          {
            "--accent": `var(--color-${guide.accent})`,
            "--accent-wash": `var(--color-${guide.accent}-wash)`,
          } as React.CSSProperties
        }
      >
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />

        <section className="relative overflow-hidden border-b border-rule bg-mist/65">
          <div className="pointer-events-none absolute -right-28 -top-24 hidden h-[30rem] w-[30rem] opacity-70 lg:block">
            <BloomingMagnolia className="h-full w-full -rotate-[14deg]" />
          </div>
          <div className="relative mx-auto max-w-3xl px-6 py-16 sm:py-20 lg:py-24">
            <RevealGroup stagger={0.09}>
              <RevealItem>
                <nav aria-label="Breadcrumb">
                  <ol className="flex flex-wrap items-center gap-x-3 gap-y-1 text-base font-bold uppercase tracking-[0.14em] text-green">
                    <li>
                      <Link
                        href="/guides"
                        className="transition-colors duration-200 hover:text-pink"
                      >
                        Guides
                      </Link>
                    </li>
                    <li aria-hidden="true" className="text-green-soft">
                      /
                    </li>
                    <li className="text-ink-faint">{guide.category}</li>
                  </ol>
                </nav>
              </RevealItem>
              <RevealItem>
                <h1 className="mt-6 text-[2.2rem] leading-[1.1] sm:text-[2.9rem] lg:text-[3.2rem]">
                  {guide.title}
                </h1>
              </RevealItem>
              <RevealItem>
                <p className="mt-6 text-2xl text-ink-soft">{guide.dek}</p>
              </RevealItem>
              <RevealItem>
                <p className="mt-8 text-base text-ink-faint">
                  By {site.founder}
                  {"  "}
                  <span aria-hidden="true">&middot;</span>{" "}
                  <time dateTime={guide.published}>
                    {formatGuideDate(guide.published)}
                  </time>{" "}
                  <span aria-hidden="true">&middot;</span> About{" "}
                  {guide.readMinutes} minutes to read
                </p>
              </RevealItem>
            </RevealGroup>
          </div>
        </section>

        <article className="mx-auto max-w-3xl px-6 py-14 sm:py-20">
          {children}

          <Sources items={sources} />

          <Reveal className="mt-16 rounded-panel border-2 border-[var(--accent)] bg-[var(--accent-wash)] p-8 sm:p-10">
            <h2 className="text-[1.8rem]">
              Rather just ask somebody?
            </h2>
            <p className="mt-4 text-xl text-ink-soft">
              Call {site.phone} and talk it through with {site.firstName}. She
              will tell you honestly what she thinks you need, even when the
              answer is not us.
            </p>
            <div className="mt-8">
              <CallButton />
            </div>
          </Reveal>

          <nav aria-label="Related pages" className="mt-14 border-t border-rule pt-8">
            <h2 className="text-base font-bold uppercase tracking-[0.18em] text-green">
              Read next
            </h2>
            <ul className="mt-5 flex flex-wrap gap-x-8 gap-y-3">
              {guide.related.map((r) => (
                <li key={r.href}>
                  <Link
                    href={r.href}
                    className="text-xl text-ink-soft underline decoration-rule decoration-2 underline-offset-4 transition-colors duration-200 hover:text-pink hover:decoration-pink-soft"
                  >
                    {r.label}
                  </Link>
                </li>
              ))}
              <li>
                <Link
                  href="/guides"
                  className="text-xl text-ink-soft underline decoration-rule decoration-2 underline-offset-4 transition-colors duration-200 hover:text-pink hover:decoration-pink-soft"
                >
                  All guides
                </Link>
              </li>
            </ul>
          </nav>
        </article>

        <ClosingCta />
      </main>
      <Footer />
    </>
  );
}
